services:
  postgres:
    image: postgres:16
    container_name: farm-monitoring-postgres
    environment:
      POSTGRES_DB: farm_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: farm-monitoring-server
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/farm_monitoring
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./farm-monitoring-server/src/main/resources/static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  emulator:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    container_name: farm-monitoring-emulator
    depends_on:
      server:
        condition: service_healthy
    environment:
      EMULATOR_SERVER_URL: http://server:8080/api
    ports:
      - "8081:8081"

volumes:
  postgres-data: 