version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: farm-monitoring-postgres
    environment:
      POSTGRES_DB: farm_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: farm-monitoring-server
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/farm_monitoring
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  emulator:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    container_name: farm-monitoring-emulator
    depends_on:
      - server
    environment:
      EMULATOR_SERVERURL: http://server:8080/api
      EMULATOR_SERVER_URL: http://server:8080/api

volumes:
  postgres-data: 